###Revising the Select Query-1
SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

###Revising the Select Query-2
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

